module.exports = {
	fr: {
		definitionButtonText: "Définitions des étiquettes",
		filterButtonText: "Filtrer les pages",
		subjectsText: "Sujets",
		tagsText: "Thèmes",
		descriptionText: "Description",
		pathText: "Chemin d'accès",
		filePathText: "Emplacement du fichier",
		resultsText: "résultats sur",
		searchText: "Rechercher",
		optionsLegend: "Options",
		hideTopicsText: "Cacher des pages de thèmes",
		rolesText: "Rôles",
		tableOptionsButton: "Colonnes et types de pages",
		columnsLegend: "Colonnes visibles",
		pageTypesLegend: "Types de pages",
		landingPagesText: "Pages d'atterrissage",
		contentPagesText: "Pages de contenu",
		downloadCsvText: "Télécharger l'export CSV",
		tableCaption: "Toutes les pages de la Boîte à outils de l'accessibilité numérique",
		noScriptText: "Le tableau nécessite JavaScript. Téléchargez l'export CSV pour consulter toutes les pages.",
		noticeTitle: "Les pages thématiques sont masquées",
		noticeText: "La liste des pages ci-dessous <strong>ne contient pas</strong> les pages thématiques. Pour les ajouter, décochez « Cacher des pages de thèmes ».",
		// Page list link component
		linkHeading: "Vous ne trouvez toujours pas ce dont vous avez besoin?",
		linkText: "liste complète des pages",
		linkPrefix: "Consultez notre",
		linkUrl: "/liste-des-pages/",
	},

	en: {
		definitionButtonText: "Definitions of labels",
		filterButtonText: "Filter pages",
		subjectsText: "Subjects",
		tagsText: "Topics",
		descriptionText: "Description",
		pathText: "Path",
		filePathText: "File location",
		resultsText: "results out of",
		searchText: "Search",
		optionsLegend: "Options",
		hideTopicsText: "Hide topic pages",
		rolesText: "Roles",
		tableOptionsButton: "Columns and page types",
		columnsLegend: "Visible columns",
		pageTypesLegend: "Page types",
		landingPagesText: "Landing pages",
		contentPagesText: "Content pages",
		downloadCsvText: "Download CSV export",
		tableCaption: "All pages in the Digital Accessibility Toolkit",
		noScriptText: "The table needs JavaScript. Download the CSV export to see every page.",
		noticeTitle: "Topic pages are hidden",
		noticeText: "The list of pages below <strong>does not list</strong> the topic pages. To add those, uncheck “Hide topic pages”.",
		// Page list link component
		linkHeading: "Still can't find what you need?",
		linkText: "complete list of pages",
		linkPrefix: "See our",
		linkUrl: "/page-list/",
	},
};
